import type { ProjectBudgetLine, ProjectBudgetLinePayload } from "../../api/erpBudgets";

export const DEFAULT_BUDGET_PAYLOAD: ProjectBudgetLinePayload = {
  concept: "",
  hito1_budget: 0,
  justified_hito1: 0,
  hito2_budget: 0,
  justified_hito2: 0,
  approved_budget: 0,
  percent_spent: 0,
  forecasted_spent: 0,
};

export const getDefaultBudgetTemplate = (): ProjectBudgetLine[] => {
  const now = new Date().toISOString();
  return [
    {
      id: -1,
      project_id: 0,
      concept: "EQUIPOS (Amortizacion)",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -2,
      project_id: 0,
      concept: "PERSONAL",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -14,
      project_id: 0,
      concept: "Doctores",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -3,
      project_id: 0,
      concept: "Titulados universitarios",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -4,
      project_id: 0,
      concept: "No titulado",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -5,
      project_id: 0,
      concept: "MATERIAL FUNGIBLE",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -6,
      project_id: 0,
      concept: "Materiales para pruebas y ensayos",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -7,
      project_id: 0,
      concept: "COLABORACIONES EXTERNAS",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -8,
      project_id: 0,
      concept: "Centros Tecnologicos",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -9,
      project_id: 0,
      concept: "GASTOS GENERALES",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -10,
      project_id: 0,
      concept: "OTROS GASTOS",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -11,
      project_id: 0,
      concept: "Auditoria",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -12,
      project_id: 0,
      concept: "Dictamen acreditado ENAC de informe DNSH",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -13,
      project_id: 0,
      concept: "Total",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
    {
      id: -15,
      project_id: 0,
      concept: "Diferencia (por justificar)",
      hito1_budget: 0,
      justified_hito1: 0,
      hito2_budget: 0,
      justified_hito2: 0,
      approved_budget: 0,
      percent_spent: 0,
      forecasted_spent: 0,
      created_at: now,
    },
  ];
};
