name: Deploy ERP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}  # opcional, si cambias el puerto
          script: |
            # Entrar a la carpeta de docker-compose
            cd ${{ secrets.DEPLOY_PATH }}

            # Actualizar código desde Git
            git pull origin main

            # Exportar variables de entorno de staging si existe
            if [ -f ${{ secrets.ADDITIONAL_ENVS }} ]; then
              export $(grep -v '^#' ${{ secrets.ADDITIONAL_ENVS }} | xargs)
            fi

            # Levantar containers con Docker Compose en modo detached
            docker compose up -d --build
